[package]
org = "chalanagayan"
name = "newsboard_backend"
version = "0.1.0"
distribution = "2201.8.6"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.7.2"
